### ISSUE TITLE
jeelink v3 newbie

### ISSUE THREAD

**Issue by habeIchVergessen** [kobuki/VPTools#1]
hi kobuki,

i started to play around with jeelink v3 and need some assistance to understand the .ino stuff.

i guess that i have understood that the .ino code
- initialize the radio interface
- processing radio data
- output to serial line

correct me if i'm wrong.

but i have no idea how to load the .ino code to the jeelink.
can you point me to tutorial?

thx

**Comment by kobuki** [comment]
Jeelink is an Arduino Uno-compatible device. I suggest you look around on the net for tutorials on the Uno and see http://jeelabs.net/ about the JeeLink. OTOH, you load the sketch as usual and pay attention to the commented basic settings, and the few statements in init(). Those should get you started with a VP2 transmitter. Your sequence is very general, albeit not wrong. The important bits are in the details.

And sorry, but this is not the right place for Arduino/AVR beginners. If you find bugs, have suggestions for improvements regarding this repo, then you're welcome, of course.

**Comment by habeIchVergessen** [comment]
i was able to upload the  sketch. your advice for the uno compatibility
made the  difference. handle vptools as  lib for adruino ide was the  last
puzzle.
thx.
Am 07.11.2015 18:31 schrieb "kobuki" notifications@github.com:
