### ISSUE TITLE
Issue with packet loss / stalling on 3 transmitters

### ISSUE THREAD

**Issue by captain-bodge** [kobuki/VPTools#10]
Hi, 

I have an issue with the WxReceiver sketch, on a Motino R4, with BMP280 sensor and 868mhz rubber aerial.
Not sure if its my config of 3 transmitters (all in UK, so EU band)

Tx1 - Wind / UV / Solar
Tx2 - Temp & Hum
Tx3 - Rain

I'm running the sketch with the following changes:

`byte cfgNumStations = 3;
....
// id, type, active
Station stations[8] = {
  { 0, STYPE_ISS, true },  
  { 1, STYPE_TEMP_HUM, true },
  { 2, STYPE_RAIN, true }
};
`

The behaviour is that the Moteino will receive OK intially, then degrade and stop. After a few mins, it will restart and the loss sequence will happen again after a random amount of time.

I amended the code to show debug info:

` Serial.print(round(rd->fei * RF69_FSTEP / 1000));
//Serial.println(round(rd->fei * RF69_FSTEP / 1000));

Serial.print(F(" stn="));
  // Other possible informational values:
    Serial.print(packet[0] & 0x7); // station
    Serial.print(F(" total="));
    Serial.print(radio.packets); // total packets
    Serial.print(F(" lost="));
    Serial.print(radio.lostPackets); // total lost packets
    Serial.print(F(" ratio="));
    Serial.println((float)(radio.packets * 100.0 / (radio.packets + radio.lostPackets))); // total good/(good+bad) packet ratio
    //Serial.print((float)(radio.packets * 100.0 / (radio.packets + radio.lostPackets))); // total good/(good+bad) packet ratio
`

This is the output with extra info, with Arduino IDE timestamps:
Issue can be seen by a stall in reception at 20:56:20

*edit - pasting results breaks formatting, see attached file.
[motino.txt](https://github.com/kobuki/VPTools/files/6947910/motino.txt)

During the stalled time, I could see the VP2 console was still receiving wind packets correctly, so doesn't seem to be an issue with the transmitters.

As a comparison, I loaded the mcrossley RelayRxTx sketch, with only changes being to my transmitter config (same as above) and with everything else the same, I didn't see the same packet loss / stalling.

Many thanks

**Comment by kobuki** [comment]
Don't configure WxReceiver in code, only when you set up one of the supported sensors. Every setting apart from that is configured via serial commands. Only change the #define statements for the sensors. Other changes are not supported with this sketch and you're on your own (unless you fix actual bugs or non-EU reception).

For example, send 't7', 'm1' commands to set it to listen to ID numbers 1, 2, 3 (the 't' command accepts a station bitmap) and the EU band. 'm1' will start the actual reception.

Note that this sketch is primarily for use with the [WeeWx driver](https://github.com/kobuki/weewx-meteoRX) ad implements a subset of the Meteostick commands (a commercial product).

**Comment by kobuki** [comment]
One thing I noticed in your log fragment is that station No. 2 (binary ID 1) is only present twice, and the 2nd time with a very low RSSI (-94). Maybe it's a bit too far for your setup. Try bringing the station and the receiver closer to each other or try increasing the RSSI threshold, something like 'x200' or 'x210'. Even 200 is a bit too much (it means a -100 dB RSSI threshold), but might worth a try.

**Comment by captain-bodge** [comment]
Hi, thanks for your replies.
I didn't realise you could just config via serial, so amended code prior to upload, sorry.
I first discovered this issue when testing using WeeWx driver; I could see the interpreted packets stalling on the log output, and ruled out everything in WeeWx & Pi4, just leaving to the Moteino.

What I've done is redownloaded the zip of the code and compiled/uploaded it without any modifications. I then started it running using just t7 then m1.
Issue still exists, see attached log at 22:21:23 where there is a stall for 37 seconds. The VP2 console was showing changing windspeed on station 1, so I would have expected to see some output from station 1 on the Motino...
The VP2 console is 1.5m away from the Motino, further away from the transmitters.

As you have identified, station 2 is the furthest transmitter, however, it's only 10m away, open air, line of sight. I think that -94 RSSI may be an outlier, as the longer extract attached shows most of the time its low 70's.
I'll try moving it tomorrow in the daylight, to see if makes a difference
[motino2.txt](https://github.com/kobuki/VPTools/files/6948115/motino2.txt)
...

**Comment by kobuki** [comment]
OK, I have no ideas then. I encountered a few flaky RFM69 radios when I assembled receivers with Moteinos or our custom boards but if RelayRxTx works fine, that shouldn't be the problem. Apart from that, we never had problems on the EU band. FEI looks good in your log, but timings are weird sometimes.

After this line:
```
22:21:11.066 -> I 104 82 00 00 FF C5 00 79 A2  -86 1296180 7
```
Station 3 disappears and only shows up after a long while, causing a long series of packet losses that trigger a full resync. Then a similar one with another impossible timing:
```
22:23:30.829 -> I 103 82 00 00 FF C5 00 79 A2  -67 4549096 2
```
But it then recovers faster. It's like there's interference from an extra station. But again, if RelayRxTx works, that should not be the case. Unless someone activated another station near you with the same ID in the meantime. To make sure, IDs of all stations could be shifted to e.g. 4, 5, 6.

**Comment by captain-bodge** [comment]
Ok, so done some more on this.
Changing TX channel to 6, 7 & 8 didn’t make any difference. As I had the ladder out, I changed the physical transmitters around. The PCB from Station 3 (rain) that you mentioned above disappearing was moved to Station 1 (wind/uv/solar) and the irregular packets have moved with it. I think there might be an issue with this transmitter. It works fine though with RelayRxTx and VP2 console still works fine, with no packet loss according to the diag screen.
Issue with pauses remains though…

I have another unused Moteino, so next step is to build that one up and give it a go…

**Comment by kobuki** [comment]
Could you try temporarily disabling the "misbehaving" transmitter in your config to see if it improves reception? Also, remove any of your own custom code, especially serial prints and set the internal sensor to emulation (instructions in the code).

**Comment by captain-bodge** [comment]
OK, first to reply to your questions above - disabling the misbehaving transmitter station 1 (used t6 rather than t7) didn’t affect anything, still caused an issue. Code was as downloaded, only change I had made was to enable the BMP280.
Setting emulation didn’t affect anything either.

BUT

I have now set up my second Moteino with the same sketch (tested with both BMP enabled and emulated) and apart from the sporadic packets from the misbehaving transmitter, it’s worlds better. It’s been running for several hours with no issues :)
RSSI has improved across all transmitters by over 10db, there are no pauses, WeeWx is working great :)

I’m hypothesising here that the dodgy Moteino threw something out in the timing that didn't matter to the RelayRxTx sketch or Davis Console, but tripped the WxReceiver sketch up…

Thanks for your help with this, sorry to waste your time.
I’ll monitor for a few days, and if it stays OK, close the issue.

Thanks again.

**Comment by kobuki** [comment]
Great! As I mentioned I also had a few (really just a few, out of several hundred various devices) Moteinos/chips or RFM69 modules that behaved similarly. Replacing the mote, the ATMega chip or the module always fixed it. Probably it would have made sense to try this earlier... Reception should be at least 95% good packets or more with your transmitters. My own 2 transmitters (ISS in backyard and anemometer TX on the roof with solar+UV) are around 98-99%. RSSI is around -70, -50, respectively.

On another note, signal quality is not at all just RSSI, you need to make sure he antenna connections, cable, antenna itself are firmly attached/screwed, soldering is also clean and stable. We had best results with 868MHz (hinged) antennas and IPEX connectors with short cables. But even a properly sized piece of wire soldered to the mote can be surprisingly good.

**Comment by captain-bodge** [comment]
Thanks for the info.
I’m still seeing intermittent issues over time, but think it’s something environmental, rather than your code…

You mentioned above on the original hardware that “ but timings are weird sometimes.” - how do you work this out from the logs?
It’s working for now, but might take a look at it when i get a bit more time, so just wondering what debugging i can do myself.

I’ll close the issue later when I get to a PC, mobile wont close for some reason.

Thanks for your help, and of course for developing the code in the first place!

**Comment by kobuki** [comment]
> intermittent issues

What do these entail?

> but timings are weird sometimes

It means that some timings of seemingly good packets are not a multiple of the base interval in your logs. In any case, I'm glad it's resolved. I've ordered a US transmitter so I'll be able to fix the non-EU band problems and also will fine-tune the timing and the freq. adjustment in the code while at it.

**Comment by captain-bodge** [comment]
The intermittent issues are packets pausing again. The reason why I think this is environmental and different to this issue is that this time the Davis console also pauses and looses packets at the same time.

Out of interest, would you foresee any issue with running this on a 32u4 at 8Mhz Feather board (with RFM69HCW)?
I want another receiver for a remote console I’m building and it’s easier to get hold of a 32u4 in the UK than a Moteino…

**Comment by kobuki** [comment]
I've never used 32u4 based devices extensively (I have a couple of old, now unused Leonardos), but I don't see why it wouldn't work. Pins are prolly the most obvious difference. The interrupt routines would take up more time but that shouldn't cause any problems. Instead of the Moteino, you could use anything 328p based you can hook an RFM69 module on. Moteino is just very well made and easy to work with together with the RFM modules.
