### ISSUE TITLE
Clarification on Vue vs. VP2

### ISSUE THREAD

**Issue by dazhbog** [kobuki/VPTools#12]
Hi, great work. I have been tracking all the different projects tackling the communication from Davis devices and your repo has great insights.

1. In the code below (Examples/ISSRx/ISSRx.ino):
```
// wind data is present in every packet, windd == 0 (packet[2] == 0) means there's no anemometer
  if (packet[2] != 0) {
    if (stations[stIx].type == STYPE_VUE) {
      val = (packet[2] << 1) | (packet[4] & 2) >> 1;
      val = round(val * 360 / 512);
    } else {
      val = 9 + round((packet[2] - 1) * 342.0 / 255.0);
    }
  }
```

What is this piece of data? Does the VUE have 1 bit of wind data in the Byte 4? Where did you find this info?
```
(packet[4] & 2) >> 1
```

2. Do you know of any way to distinguish from VP2 and VUE. I am looking for a way to autodetect the stations[].type (STYPE)

Thank you so much!

**Comment by kobuki** [comment]
1. Discovering the packet structure is the work of many people who helped with decoding (not just in this project, several others as well), I can't really tell any more who discovered what, even including myself. You can verify the decoding yourself if you have a Vue to test with.

2. As far as I'm aware, there's no direct way to detect the station type. You can probably use some heuristics, though, by analyzing the packet stream. Some packet types are only broadcasted from the Vue. But going that route would slow down syncing to the station, so it's a compromise.
