### ISSUE TITLE
Moteino reset after radio.initialize()

### ISSUE THREAD

**Issue by manmoi01** [kobuki/VPTools#2]
Hi. 
First of all thanks for the bookshop at my university we have some consoles VP2, so I'm trying to use to display data. However, when trying to use anemometertx.ino included in the latest version of the library the moteino restarts at the instruction of initializate (),  if I use a previous version i can send data between two moteinos https://github.com/kobuki/VPTools/tree/f13ab5e11f02d7715f92156d70d30ebe7ba88d0a

best regards 
manmoi01

**Comment by kobuki** [comment]
A note: if you use the sketch for anemometers, don't use the wind error correction routines. The lookup table is no good. I'll release a better version in the future.

**Comment by manmoi01** [comment]
kobuki

thanks for the answer, today I tasted the new code and works with a repeater davis, in a few days I hope to try it with a VP2 console.
