### ISSUE TITLE
documenting packet formats

### ISSUE THREAD

**Issue by amm042** [kobuki/VPTools#4]
Great work building on dekay's project. Can you add more comments about the additional packet formats you have decoded? Specifically, VP2P_RAINSECS, VUEP_VCAP, VUEP_VSOLAR (these are pretty self explanatory but..), and VP2P_WINDGUST. For WINDGUST what is the gustref value for? 

thanks.

**Comment by kobuki** [comment]
I appreciate your comment but your wording feels like I've done nothing much than amend his code. Well, that's far from the truth with about 80% of my original code and the vast functionality added/fixed, but whatever. For more docs I suggest registering on WXForum. I can't promise more details in the code in the near future, though not impossible.
