### ISSUE TITLE
WXReceiver problem

### ISSUE THREAD

**Issue by toitoine-1997** [kobuki/VPTools#8]
Good evening, first of all congratulations on your work. Here I have a little problem with the wxreceiver sketch, I make the necessary configurations so that it works, so my installation works with a moteino RFM69HCW, BMP180. The frequency is set to EU (I live in Belgium). When I start the serial monitor I only have this:
-> # WxReceiver v2019122001 ready to accept commands
->?

when i type an order i have this: -> #ERR

Now with the ISSRx sketch I see the raw data

If anyone has an idea thank you in advance

Good evening to all

**Comment by kobuki** [comment]
A sequence of '?' and '\n' should answer with a line of the current settings. Make sure your terminal client doesn't send unnecessary characters. You can use eg. Putty on windows, Python miniterm on any OS to talk to the firmware, the Arduino IDE won't do.

**Comment by toitoine-1997** [comment]
Thank you for your response, I tried with the Putty command and here are the returns I got the 1st command is "?" which returns me OK but then I made a command "o" and "t".
`# WxReceiver v2019122001 ready to accept commands`
`?`
`# OK t1 f1 o0 m1 x190 r0 stopped`
`# ERR unimplemented`
`# ERR`

When searching the web for feedback I should have the following:
`# OK listening to 1`
`# OK band EU`

but none of that, I don't see where the problem will come from?

I even tried with the meteostick driver on weewx but it remains blocked each time on "Starting main packet loop" once launched

**Comment by kobuki** [comment]
You need to enter commands as shown by the `?` command, like `f1`, `o0`, etc. The command set is largely a subset of that of the Meteostick. No docs, please see the source. It's not really made to be used by manual commands, but possible. It's mainly for scripts to interact with, like the WeeWx driver [here](https://github.com/kobuki/weewx-meteoRX).

**Comment by toitoine-1997** [comment]
Ah okay I understand better now sorry for the inconvenience ...
In terms of communication with weewx you have no idea why it remains stuck on "Starting main packet loop"?

**Comment by kobuki** [comment]
From this alone, no, enable debug logs so see more.

**Comment by kobuki** [comment]
@toitoine-1997 

>  In terms of communication with weewx you have no idea why it remains stuck on "Starting main packet loop"?

Please try again now with the weewx-meteoRX driver. It had issues with serial comms. under Python 3, they're now fixed.
